### PR TITLE
Fix/#15 replace panic with result

### LINKED ISSUE #15: Replace panic! with Result
## Description

Replace the usage of `panic!` with `Result` in several locations within the project to handle errors more appropriately and provide better error messages.

### PR DESCRIPTION
**Pull request by sheagrief**
fix #15

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -44,11 +44,35 @@ struct Output {
...
+    let file = File::create("./outputs/outputs.json")?;
+    Ok(file)
+}
+
+fn write_data(file: &mut File, data: &[u8]) -> Result<(), std::io::Error> {
+    file.write_all(data)?;
+    Ok(())
+}
+
 fn main() {
```
Comment (taskooh) [inline src/main.rs:65]: Lets return Result type like this.
```
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    // プログラムのメインロジックを記述

    // エラーが発生した場合はResultのErrを返す
    // 例: ファイルの読み込みに失敗した場合
    // return Err(Box::new(io::Error::new(io::ErrorKind::Other, "ファイルを読み込めませんでした")));
    
    // エラーがない場合はResultのOkを返す
    Ok(())
}
```
